# Report-Microsoft365GroupsExpiration.PS1
# A script to show how to use the Microsoft Graph PowerShell SDK to report on the expiration of Microsoft 365 groups.

# V1.0 21-Nov-2024
# GitHub link: 


# An example script used to illustrate a concept. More information about the topic can be found in the Office 365 for IT Pros eBook https://gum.co/O365IT/
# and/or a relevant article on https://office365itpros.com or https://www.practical365.com. See our post about the Office 365 for IT Pros repository 
# https://office365itpros.com/office-365-github-repository/ for information about the scripts we write.

# Do not use our scripts in production until you are satisfied that the code meets the needs of your organization. Never run any code downloaded from the Internet without
# first validating the code in a non-production environment.